//go:build !wasm

package actionbutton

import . "github.com/tinywasm/css"

func SSRInstance() *ActionButton { return &ActionButton{} }

func (b *ActionButton) RenderCSS() *Stylesheet {
	return New(
		Rule(clsBtnUrlUp,
			RuleContent(Decl{Prop: "margin-bottom", Val: "auto"}),
		),
		Rule(clsBtnUrlDown,
			RuleContent(Decl{Prop: "margin-top", Val: "auto"}),
			RuleContent(Decl{Prop: "margin-bottom", Val: ".3rem"}),
		),
		Rule(Selector("."+string(clsBtnUrlDown)+" ."+string(clsBtnUrl)),
			BackgroundColor(ColorBackground),
		),
		Rule(Selector("."+string(clsBtnUrlDown)+" svg."+string(clsBtnUrl)+" path"),
			RuleContent(Decl{Prop: "fill", Val: ColorPrimary.Var()}),
		),
		Rule("button",
			Cursor(Pointer),
			Border(None),
			Outline(None),
		),
		Rule(Selector("button[name*=\"btn\"]"),
			RuleContent(Decl{Prop: "background-position", Val: "center"}),
			RuleContent(Decl{Prop: "background-size", Val: "12%"}),
			RuleContent(Decl{Prop: "background-repeat", Val: "no-repeat"}),
			BackgroundColor(ColorPrimary),
			Color(ColorOnPrimary),
			Padding(Rem(0.4)),
			BorderRadius(Em(0.4)),
			Flex(Auto),
			Margin(Em(0.25)),
		),
		Rule(Selector("button[name*=\"btn\"]:disabled"),
			BackgroundColor(ColorMuted),
			PointerEvents(None),
		),
		Rule(Selector("button[name*=\"btn\"]:hover"),
			BackgroundColor(ColorSecondary),
		),
		Rule(Selector("button[name=\"btn_crudnew\"]"),
			BackgroundImage(Str("url(\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIGNsYXNzPSdidG5fY3J1ZG5ldycgdmlld0JveD0nMCAwIDE2IDE2Jz4KPHBhdGggZmlsbD0iI2ZmZmZmZiIgZD0iTTE1LjUgNmgtNS41di01LjVjMC0wLjI3Ni0wLjIyNC0wLjUtMC41LTAuNWgtM2MtMC4yNzYgMC0wLjUgMC4yMjQtMC41IDAuNXY1LjVoLTUuNWMtMC4yNzYgMC0wLjUgMC4yMjQtMC41IDAuNXYzYzAgMC4yNzYgMC4yMjQgMC41IDAuNSAwLjVoNS41djUuNWMwIDAuMjc2IDAuMjI0IDAuNSAwLjUgMC41aDNjMC4yNzYgMCAwLjUtMC4yMjQgMC41LTAuNXYtNS41aDUuNWMwLjI3NiAwIDAuNS0wLjIyNCAwLjUtMC41di0zYzAtMC4yNzYtMC4yMjQtMC41LTAuNS0wLjV6Ii8+Cjwvc3ZnPg==\")")),
		),
		Rule(Selector("button[name=\"btn_cruddel\"]"),
			BackgroundImage(Str("url(\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIGNsYXNzPSdidG5fY3J1ZGRlbCcgdmlld0JveD0nMCAwIDE2IDE2Jz4KPHBhdGggZmlsbD0iI2ZmZmZmZiIgZD0iTTAgNi41djNjMCAwLjI3NiAwLjIyNCAwLjUgMC41IDAuNWgxNWMwLjI3NiAwIDAuNS0wLjIyNCAwLjUtMC41di0zYzAtMC4yNzYtMC4yMjQtMC41LTAuNS0wLjVoLTE1Yy0wLjI3NiAwLTAuNSAwLjIyNC0wLjUgMC41eiIvPgo8L3N2Zz4=\")")),
		),
		Rule(clsContebuton,
			Display(Flex_),
			Height(Pct(100)),
			Background(ColorSurface),
			JustifyContent(Str("space-between")),
			RuleContent(Decl{Prop: "margin-left", Val: Space1.Var()}),
			Padding(Em(0.1)),
			BorderRadius(Em(0), Em(0), Em(0.4), Em(0.4)),
		),
		Rule(clsContCenteredBtn,
			RuleContent(Decl{Prop: "margin-top", Val: "0.5em"}),
			Display(Flex_),
			Height(Em(3)),
			Width(Pct(100)),
		),
		Rule(Selector("button[name=\"btn_crudcancel\"]"),
			BackgroundImage(Str("url(\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIGNsYXNzPSdidG5fY3J1ZGNhbmNlbCcgdmlld0JveD0nMCAwIDE2IDE2Jz4KPHBhdGggZmlsbD0iI2ZmZmZmZiIgZD0iTTggMWMtMi4yMDkgMC00LjIwOSAwLjg5Ni01LjY1NyAyLjM0M2wtMi4zNDMtMi4zNDN2Nmg2bC0yLjI0My0yLjI0M2MxLjA4Ni0xLjA4NiAyLjU4Ni0xLjc1NyA0LjI0My0xLjc1NyAzLjMxNCAwIDYgMi42ODYgNiA2IDAgMS43OTItMC43ODYgMy40MDEtMi4wMzIgNC41bDEuMzIzIDEuNWMxLjY2MS0xLjQ2NiAyLjcwOS0zLjYxMSAyLjcwOS02IDAtNC40MTgtMy41ODItOC04LTh6Ii8+Cjwvc3ZnPg==\")")),
		),
		Rule(Selector("button[name=\"btn_crudsave\"]"),
			BackgroundImage(Str("url(\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIGNsYXNzPSdidG5fY3J1ZHNhdmUnIHZpZXdCb3g9JzAgMCAxNiAxNic+CjxwYXRoIGZpbGw9IiNmZmZmZmYiIGQ9Ik0xNCAwaC0xNHYxNmgxNnYtMTRsLTItMnpNOCAyaDJ2NGgtMnYtNHpNMTQgMTRoLTEydi0xMmgxdjVoOXYtNWgxLjE3MmwwLjgyOCAwLjgyOHYxMS4xNzJ6Ii8+Cjwvc3ZnPg==\")")),
		),
		Rule(Selector("button[name=\"btn-login\"]"),
			BackgroundImage(Str("url(\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIGNsYXNzPSdidG4tbG9naW4nIHZpZXdCb3g9JzAgMCAxNiAxNic+CjxwYXRoIGZpbGw9IiNmZmZmZmYiIGQ9Im0xLjEgNS4yYzEuNiA0LjYgNC4xLTEuNiA1LjYgMCAwLjE4IDAuMTggMC4zMyAwLjM2IDAuNDcgMC41Nmg2LjhsMS43IDEuN2MwLjMxIDAuMzEgMC4zMSAwLjgxIDAgMS4xbC0wLjU2IDAuNTYtMC41Ni0wLjU2LTEuMSAxLjEtMS4xLTEuMS0xLjEgMS4xLTEuMS0xLjEtMS4xIDEuMWgtMS41Yy0wLjE5IDAuNDEtMC40NSAwLjc5LTAuNzkgMS4xLTEuNiAxLjYtNC4xIDEuNi01LjYgMC0xLjYtMS42LTEuNi00LjEgMC01LjZ6bTIgMy42YzAuNDctMC40NiAwLjQ3LTEuMiAwLTEuNy0wLjQ3LTAuNDYtMS4yLTAuNDYtMS43IDAtMC40NyAwLjQ2LTAuNDcgMS4yIDAgMS43IDAuNDcgMC40NiAxLjIgMC40NiAxLjcgMHoiIHN0cm9rZS13aWR0aD0iLjc5Ii8+Cjwvc3ZnPg==\")")),
		),
		Rule(Selector("button[name=\"btn_crudsend\"]"),
			BackgroundImage(Str("url(\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIGNsYXNzPSdidG5fY3J1ZHNlbmQnIHZpZXdCb3g9JzAgMCAxNiAxNic+CjxwYXRoIGZpbGw9IiNmZmZmZmYiIGQ9Im04LjUgMTZjLTAuMDM2IDAtMC4wNzItNGUtMyAtMC4xMDgtMC4wMTItMC4yMjktMC4wNTEtMC4zOTItMC4yNTQtMC4zOTIdMC40ODggMC4yMTY1LTkuMDE4IDEuMDkyLTcuNS03LjUtNy41LTAuMjM0IDAtMC40MzctMC4xNjMtMC40ODgtMC4zOTJzMC4wNjQtMC40NjIgMC4yNzctMC41NjFsMTUtN2MwLjE5MS0wLjA4OSAwLjQxNi0wLjA0OSAwLjU2NSAwLjFzMC4xODggMC4zNzQgMC4xIDAuNTY1bC03IDE1Yy0wLjA4MyAwLjE3OS0wLjI2MiAwLjI4OS0wLjQ1MyAwLjI4OXptLTUuNzQ2LTljLTEuODM2LTQuNjY3LTAuOTE4LTIuMzMzIDAgMHoiLz4KPC9zdmc+\")")),
			RuleContent(Decl{Prop: "background-size", Val: "25%"}),
			Width(Pct(20)),
		),
		Rule(Selector("."+string(clsBtnUrl)+", ."+string(clsBtnSelected)+", ."+string(clsBtnUrlDisable)+", ."+string(clsBtnLogin)),
			BoxShadow(Str(".1em .1em .2em "+ColorSurface.Var())),
			Height(Rem(2.5)),
			BorderRadius(RadiusSm),
			Padding(Em(0.3)),
		),
		Rule(Selector("."+string(clsBtnUrl)+", ."+string(clsBtnUrlDisable)+", ."+string(clsBtnSelected)),
			RuleContent(Decl{Prop: "margin-top", Val: Space2.Var()}),
		),
		Rule(clsBtnUrlDisable,
			PointerEvents(None),
			Background(ColorMuted),
		),
		Rule(Selector("."+string(clsBtnUrl)+", ."+string(clsBtnLogin)),
			Background(ColorPrimary),
		),
		Rule(clsBtnSelected,
			Background(ColorSecondary),
		),
		Rule("input[type=submit]",
			BackgroundColor(ColorPrimary),
			Color(ColorOnPrimary),
			Cursor(Pointer),
			Border(None),
			Padding(Em(0.4), Em(0.8)),
			BorderRadius(Em(0.4)),
		),
		Rule(clsBtnUrlPulse,
			BoxShadow(Str(".1rem .1rem .2rem "+ColorSurface.Var())),
			Height(Rem(2.5)),
			BorderRadius(RadiusSm),
			Padding(Em(0.3)),
			Background(ColorMuted),
			RuleContent(Decl{Prop: "margin-top", Val: Space1.Var()}),
			Animation(Str("pulse-url 2s infinite")),
		),
		Keyframes("pulse-url",
			At("0%",
				Decl{Prop: "transform", Val: "scale(0.90)"},
				Decl{Prop: "box-shadow", Val: "0 0 0 0 color-mix(in srgb, " + ColorSecondary.Var() + ", transparent 30%)"},
			),
			At("70%",
				Decl{Prop: "transform", Val: "scale(1)"},
				Decl{Prop: "box-shadow", Val: "0 0 0 1vw transparent"},
			),
			At("100%",
				Background(ColorSecondary),
				Decl{Prop: "transform", Val: "scale(0.90)"},
				Decl{Prop: "box-shadow", Val: "0 0 0 0 transparent"},
			),
		),
		Rule(clsBtn,
			Padding(Rem(0.5), Rem(1)),
			Border(None),
			BorderRadius(Rem(0.25)),
			Cursor(Pointer),
			FontSize(Rem(1)),
		),
		Rule(clsBtnPrimary,
			Background(ColorPrimary),
			Color(ColorOnPrimary),
		),
		Rule(clsBtnSecondary,
			Background(ColorMuted),
			Color(ColorOnSurface),
		),
		Rule(clsBtnDanger,
			Background(ColorError),
			Color(ColorOnSurface),
		),
		Rule(clsBtn.Hover(),
			Opacity(0.9),
		),
	)
}

func (b *ActionButton) IconSvg() map[string]string {
	return nil
}
