//go:build wasm

// web/client.go — WebAssembly entry point for this module.
// Auto-generated by webtyp when this file does not exist.
// Compiled to web/public/client.wasm and served on port 8080.
//
// DOM access: use webtyp.com/dom — https://pkg.go.dev/webtyp.com/dom
// Do NOT use syscall/js directly; webtyp/dom wraps it with a builder API.
//
// Compilation modes (L/M/S) are managed by webtyp — https://pkg.go.dev/webtyp.com/app
// For M and S modes (TinyGo): avoid all Go stdlib — use webtyp/* replacements (see table above).

package main

import (
	"webtyp.com/components/selectsearch" // https://pkg.go.dev/webtyp.com/components/selectsearch
	"webtyp.com/components/themetoggle"
	. "webtyp.com/dom" // https://pkg.go.dev/webtyp.com/dom
	. "webtyp.com/html"
)

type App struct {
	Element
	ss       selectsearch.SelectSearch
	selected *SignalString
}

func (a *App) Init(_ Ctx) {
	a.selected = NewString("")
	a.ss.Placeholder = "Choose a fruit..."
	a.ss.Options = []selectsearch.SsOption{
		{ID: "1", Label: "Apple", Description: "fruit"},
		{ID: "2", Label: "Banana", Description: "fruit"},
		{ID: "3", Label: "Cherry", Description: "fruit"},
		{ID: "4", Label: "Mango", Description: "tropical"},
		{ID: "5", Label: "Pineapple", Description: "tropical"},
	}
	a.ss.OnSelect = func(id, description string) {
		a.selected.Set(id)
	}
}

func (a *App) Render() *Element {
	result := P().ID("app-result").BindTextFunc(func() string {
		if id := a.selected.Get(); id != "" {
			return "Selected ID: " + id
		}
		return "Selected ID: —"
	})

	return Div().Child(
		H1().Text("SelectSearch"),
		&a.ss,
		result,
	)
}

func main() {
	ts := &themetoggle.ThemeToggle{}
	Render("app", &App{})
	Append("body", ts)

	// select{} keeps the WASM goroutine alive so JS event callbacks keep working.
	select {}
}
