//go:build wasm

// web/client.go — WebAssembly entry point for this module.
// Auto-generated by tinywasm when this file does not exist.
// Compiled to web/public/client.wasm and served on port 6060.
//
// DOM access: use github.com/tinywasm/dom — https://pkg.go.dev/github.com/tinywasm/dom
// Do NOT use syscall/js directly; tinywasm/dom wraps it with a builder API.
//
// Compilation modes (L/M/S) are managed by tinywasm — https://pkg.go.dev/github.com/tinywasm/app
// For M and S modes (TinyGo): avoid all Go stdlib — use tinywasm/* replacements (see table above).

package main

import (
	"github.com/tinywasm/components/selectsearch" // https://pkg.go.dev/github.com/tinywasm/components/selectsearch
	"github.com/tinywasm/components/themetoggle"
	. "github.com/tinywasm/dom" // https://pkg.go.dev/github.com/tinywasm/dom
	. "github.com/tinywasm/html"
)

type App struct {
	Element
	ss       selectsearch.SelectSearch
	selected string
}

func (a *App) Render() *Element {
	// ss lives in App state so its ID and listeners survive re-renders.
	if len(a.ss.Options) == 0 {
		a.ss.Placeholder = "Choose a fruit..."
		a.ss.Options = []selectsearch.SsOption{
			{ID: "1", Label: "Apple 2", Description: "fruit"},
			{ID: "2", Label: "Banana", Description: "fruit"},
			{ID: "3", Label: "Cherry", Description: "fruit"},
			{ID: "4", Label: "Mango", Description: "tropical"},
			{ID: "5", Label: "Pineapple", Description: "tropical"},
		}
		a.ss.OnSelect = func(id, description string) {
			a.selected = id
			a.Update()
		}
	}

	result := P("Selected ID: —")
	if a.selected != "" {
		result = P("Selected ID: ", a.selected)
	}

	return Div(
		H1("SelectSearch"),
		&a.ss,
		result,
	)
}

func main() {
	ts := &themetoggle.ThemeToggle{}
	Render("app", &App{})
	Append("body", ts)

	// select{} keeps the WASM goroutine alive so JS event callbacks keep working.
	select {}
}
